joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

right_arm_controller:
  type: "joint_trajectory_controller/JointTrajectoryController"
  joints: ['leg_right_joint_1','leg_right_joint_2','leg_right_joint_3','leg_right_joint_4','leg_right_joint_5','leg_right_joint_6','leg_right_joint_7']
  constraints:
    goal_time: 1.0
  state_publish_rate: 100
  action_monitor_rate: 50
