loop_frequency: 500
cycle_time_error_threshold: 0.002
thread_priority: 95
power_limit: 6
contact_threshold: 200

joint_modules:
  - name: neck_left
    enabled: true
    joints: [neck_left_joint_1, neck_left_joint_2, neck_left_joint_3, neck_left_joint_4, neck_left_joint_5, neck_left_joint_6, neck_left_joint_7]
    directions: [1, 1, -1, 1, 1, -1, 1]
  - name: neck_right
    enabled: true
    joints: [neck_right_joint_1, neck_right_joint_2, neck_right_joint_3, neck_right_joint_4, neck_right_joint_5, neck_right_joint_6, neck_right_joint_7]
    directions: [-1, -1, -1, 1, 1, -1, 1]

joint_names: [neck_left_joint_1, neck_left_joint_2, neck_left_joint_3, neck_left_joint_4, neck_left_joint_5, neck_left_joint_6, neck_left_joint_7,
              neck_right_joint_1, neck_right_joint_2, neck_right_joint_3, neck_right_joint_4, neck_right_joint_5, neck_right_joint_6, neck_right_joint_7]
joint_directions: [1, 1, -1, 1, 1, -1, 1,
                   -1, -1, -1, 1, 1, -1, 1]

# 关节索引 -> 实际电机 CAN ID 映射（-1 表示禁用该关节）。
motor_id_map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
