loop_frequency: 500
cycle_time_error_threshold: 0.002
thread_priority: 95
power_limit: 6
contact_threshold: 200
joint_names: [leg_l1_joint, leg_l2_joint, leg_l3_joint, leg_l4_joint, leg_l5_joint, leg_l6_joint, leg_l7_joint,
              leg_r1_joint, leg_r2_joint, leg_r3_joint, leg_r4_joint, leg_r5_joint, leg_r6_joint, leg_r7_joint]

