loop_frequency: 500
cycle_time_error_threshold: 0.002
thread_priority: 95
power_limit: 6
contact_threshold: 200

joint_modules:
  - name: leg_left
    enabled: true
    joints: [leg_left_joint_1, leg_left_joint_2, leg_left_joint_3, leg_left_joint_4, leg_left_joint_5, leg_left_joint_6, leg_left_joint_7]
    directions: [1, 1, -1, 1, 1, -1, 1]
  - name: leg_right
    enabled: true
    joints: [leg_right_joint_1, leg_right_joint_2, leg_right_joint_3, leg_right_joint_4, leg_right_joint_5, leg_right_joint_6, leg_right_joint_7]
    directions: [-1, -1, -1, 1, 1, -1, 1]

# 扁平化后的数据，便于其它节点读取
joint_names: [leg_left_joint_1, leg_left_joint_2, leg_left_joint_3, leg_left_joint_4, leg_left_joint_5, leg_left_joint_6, leg_left_joint_7,
              leg_right_joint_1, leg_right_joint_2, leg_right_joint_3, leg_right_joint_4, leg_right_joint_5, leg_right_joint_6, leg_right_joint_7]
joint_directions: [1, 1, -1, 1, 1, -1, 1,
                   -1, -1, -1, 1, 1, -1, 1]
