legs:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200
  legs_left_controller:
    type: simple_hjc/AllJointsHybridController
    joints: [leg_left_joint_1, leg_left_joint_2, leg_left_joint_3, leg_left_joint_4, leg_left_joint_5, leg_left_joint_6, leg_left_joint_7]
    default_kp: 20.0
    default_kd: 1.0
    default_vel: 0.0
    default_ff: 0.0
  legs_right_controller:
    type: simple_hjc/AllJointsHybridController
    joints: [leg_right_joint_1, leg_right_joint_2, leg_right_joint_3, leg_right_joint_4, leg_right_joint_5, leg_right_joint_6, leg_right_joint_7]
    default_kp: 20.0
    default_kd: 1.0
    default_vel: 0.0
    default_ff: 0.0

arms:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200
  arms_left_controller:
    type: simple_hjc/AllJointsHybridController
    joints: [arm_left_joint_1, arm_left_joint_2, arm_left_joint_3, arm_left_joint_4, arm_left_joint_5, arm_left_joint_6, arm_left_joint_7]
    default_kp: 20.0
    default_kd: 1.0
    default_vel: 0.0
    default_ff: 0.0
  arms_right_controller:
    type: simple_hjc/AllJointsHybridController
    joints: [arm_right_joint_1, arm_right_joint_2, arm_right_joint_3, arm_right_joint_4, arm_right_joint_5, arm_right_joint_6, arm_right_joint_7]
    default_kp: 20.0
    default_kd: 1.0
    default_vel: 0.0
    default_ff: 0.0

neck:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200
  neck_left_controller:
    type: simple_hjc/AllJointsHybridController
    joints: [neck_left_joint_1, neck_left_joint_2, neck_left_joint_3, neck_left_joint_4, neck_left_joint_5, neck_left_joint_6, neck_left_joint_7]
    default_kp: 20.0
    default_kd: 1.0
    default_vel: 0.0
    default_ff: 0.0
  neck_right_controller:
    type: simple_hjc/AllJointsHybridController
    joints: [neck_right_joint_1, neck_right_joint_2, neck_right_joint_3, neck_right_joint_4, neck_right_joint_5, neck_right_joint_6, neck_right_joint_7]
    default_kp: 20.0
    default_kd: 1.0
    default_vel: 0.0
    default_ff: 0.0

waist:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200
  waist_controller:
    type: simple_hjc/AllJointsHybridController
    joints: [waist_yaw_joint]
    default_kp: 20.0
    default_kd: 1.0
    default_vel: 0.0
    default_ff: 0.0
