controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - leg_right_joint_1
      - leg_right_joint_2
      - leg_right_joint_3
      - leg_right_joint_4
      - leg_right_joint_5
      - leg_right_joint_6
      - leg_right_joint_7
initial:  # Define initial robot poses per group
#  - group: right_arm
#    pose: home

  []