right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - leg_right_joint_1
    - leg_right_joint_2
    - leg_right_joint_3
    - leg_right_joint_4
    - leg_right_joint_5
    - leg_right_joint_6
    - leg_right_joint_7
  gains:
    leg_right_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_right_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_right_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_right_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_right_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_right_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    leg_right_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1