controller_list:
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - leg_right_joint_1
      - leg_right_joint_2
      - leg_right_joint_3
      - leg_right_joint_4
      - leg_right_joint_5
      - leg_right_joint_6
      - leg_right_joint_7